Reads and parses fNIRS data with traditional ML techniques

In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
import os
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [2]:
BASELINE_START = "baselinestart"
BASELINE_END = "baselineend"
EASY_START = "easystart"
EASY_END = "easyend"
HARD_START = "hardstart"
HARD_END = "hardend"

In [3]:
fnirs_path = os.path.join(os.getcwd(), "data/S902/2015-02-26_11-24-48-120", "fNIRSdata.txt")
marker_path = os.path.join(os.getcwd(), "data/S902/2015-02-26_11-24-48-120", "markers.txt")

First read the files

In [4]:
"""Gets the row blocks for easy and hard tasks
"""
def read_data(fnirs_path, marker_path):
    fnirs_df =  pd.read_csv(fnirs_path, sep='\t', skiprows=range(4), index_col=False)
    marker_df = pd.read_csv(marker_path, sep='\t', skiprows=range(4), index_col=False)
    
    merged_df = pd.merge(fnirs_df, marker_df, on="Matlab_now", how="left")
    
    
    return merged_df

In [5]:
def get_row_blocks(merged_df):
    easy_start_rows = merged_df.index[merged_df.Stimulus_Label == EASY_START].tolist()
    easy_end_rows = merged_df.index[merged_df.Stimulus_Label == EASY_END].tolist()
    hard_start_rows = merged_df.index[merged_df.Stimulus_Label == HARD_START].tolist()
    hard_end_rows = merged_df.index[merged_df.Stimulus_Label == HARD_END].tolist()
    
    easy_rows = list(zip(easy_start_rows, easy_end_rows))
    hard_rows = list(zip(hard_start_rows, hard_end_rows))
    
    return (easy_rows, hard_rows)

In [6]:
"""Return subset of df determined by the indices of the row blocks
"""
def get_subsets(merged_df, row_blocks):
    tables = []
    column_names = ["Matlab_now", "A-DC1", "A-DC2", "A-DC3", "A-DC4", "A-DC5",
                    "A-DC6", "A-DC7", "A-DC8", "B-DC1", "B-DC2", "B-DC3", 
                    "B-DC4", "B-DC5", "B-DC6", "B-DC7", "B-DC8"]
    column_indices = [merged_df.columns.get_loc(c) for c in column_names]
    for row_block in row_blocks:
        df = merged_df.iloc[row_block[0]:row_block[1], column_indices]
        start_time = df.iloc[0]["Matlab_now"]
        df["Matlab_now"] = df["Matlab_now"] - start_time

        tables.append(df)
    return tables

In [7]:
"""Perform linear fit and calculate linear fit coefficients and mean
    :param table: pandas df, subset to examine
    :return: Dictionary of
                key: Column name
                value: 3-tuple (a, b, mean), where y = ax + b
"""
def extract_feature(table):
    x = table["Matlab_now"].values
    cols = table.columns[1:]
    my_dict = {}
    for col in cols:
        y = table[col].values
        z = np.poly1d(np.polyfit(x, y, 1))
        my_tuple = (z[1], z[0], table[col].mean())

        my_dict[col] = my_tuple
    return my_dict

In [8]:
"""runs polyfit on the timeseries data
    :param tables: table of blocks of easy / hard tasks
    :param difficulty: 0 - easy, 1 - hard; labeling process
    
    :return: numpy array of
    feature_row: 
        AC-1 gradient, AC-1 intercept, AC-1 mean, AC-2 gradient ... DC-8 gradient DC-8 intercept DC-8 mean difficulty
    
    
    Dictionary of key: channel
                           value: (gradient, mean, difficulty)
"""
def extract_features(tables, difficulty):
    arr = np.empty((0, 49))
    for table in tables:
        x = table["Matlab_now"].values
        cols = table.columns[1:]
        feature_row = []
        for col in cols:
            y = table[col].values
            gradient, intercept = np.poly1d(np.polyfit(x, y, 1))
            avg = table[col].mean()
            
            feature_row = feature_row + [gradient, intercept, avg]
        feature_row.append(difficulty)
        feature_row = np.array(feature_row)
        
        arr = np.vstack([arr, feature_row])
    return arr
        

In [9]:
"""Extract features from given dataset
    :param data_path: Directory containing the files
    
    :return: gets all the easy and hard features from a given dataset
"""
def get_features_for_dataset(data_path):
    fnirs_path = os.path.join(os.getcwd(), data_path, "fNIRSdata.txt")
    marker_path = os.path.join(os.getcwd(), data_path, "markers.txt")
    merged_df = read_data(fnirs_path, marker_path)
    easy_rows, hard_rows = get_row_blocks(merged_df)
    
    easy_tables = get_subsets(merged_df, easy_rows)
    hard_tables = get_subsets(merged_df, hard_rows)
    easy_feature_rows = extract_features(easy_tables, 0)
    hard_feature_rows = extract_features(hard_tables, 1)
    
    features = np.vstack([easy_feature_rows, hard_feature_rows])

    return features

In [10]:
get_features_for_dataset("/Users/sjjin/workspace/hci_lab/data/S902/2015-02-26_11-24-48-120")

array([[-1.98423547e+00,  1.88085852e+03,  1.85117232e+03, ...,
         1.25560231e+01,  1.23240395e+01,  0.00000000e+00],
       [-3.85560577e-01,  1.84479211e+03,  1.83903966e+03, ...,
         1.26342789e+01,  1.24279037e+01,  0.00000000e+00],
       [-1.47441570e+00,  1.86788622e+03,  1.84582203e+03, ...,
         1.23430331e+01,  1.23145198e+01,  0.00000000e+00],
       ...,
       [ 2.10889695e+00,  1.65531971e+03,  1.68682203e+03, ...,
         1.12960403e+01,  1.15924294e+01,  1.00000000e+00],
       [-8.11446930e-01,  1.70379200e+03,  1.69170822e+03, ...,
         1.15253817e+01,  1.16490652e+01,  1.00000000e+00],
       [-4.35653114e-01,  1.67908834e+03,  1.67258475e+03, ...,
         1.18857171e+01,  1.16263842e+01,  1.00000000e+00]])

In [11]:
data_path = "/Users/sjjin/workspace/hci_lab/data/S902/2015-02-26_11-24-48-120"
fnirs_path = os.path.join(os.getcwd(), data_path, "fNIRSdata.txt")
marker_path = os.path.join(os.getcwd(), data_path, "markers.txt")
merged_df = read_data(fnirs_path, marker_path)
easy_rows, hard_rows = get_row_blocks(merged_df)
easy_tables = get_subsets(merged_df, easy_rows)

In [12]:
len(easy_tables)

11

In [13]:
easy_tables[0]

Matlab_now   A-DC1  A-DC2  A-DC3  A-DC4   A-DC5  A-DC6  A-DC7  A-DC8  \
1111       0.000  1885.0  478.9  131.2  40.20  1800.0  441.0  110.2  28.98   
1112       0.062  1896.0  472.0  131.3  40.10  1805.0  440.4  110.3  29.07   
1113       0.126  1882.0  478.3  131.8  40.22  1804.0  441.7  110.8  28.86   
1114       0.264  1885.0  474.8  131.1  40.17  1802.0  442.2  110.1  29.03   
1115       0.329  1886.0  476.7  130.4  39.66  1804.0  440.2  110.7  28.92   
1116       0.467  1883.0  473.3  130.6  39.77  1809.0  440.9  109.9  29.02   
1117       0.533  1883.0  479.3  130.4  40.07  1806.0  441.3  111.0  29.10   
1118       0.608  1877.0  475.9  130.0  40.21  1797.0  443.5  110.7  28.91   
1119       0.670  1880.0  474.1  130.7  40.00  1805.0  442.0  111.2  29.12   
1120       0.732  1901.0  475.7  130.8  40.19  1803.0  443.0  111.1  29.14   
1121       0.857  1897.0  481.2  131.7  40.43  1812.0  442.3  111.4  29.05   
1122       0.923  1890.0  476.5  131.8  39.94  1803.0  445.1  111.5  29.20   
1123       0.998  1879.0  473.3  131.3  39.88  1805.0  441.1  111.2  29.01   
1124       1.060  1884.0  475.6  130.8  39.78  1810.0  443.8  111.1  29.06   
1125       1.185  1880.0  475.8  130.3  39.84  1809.0  442.8  110.8  29.14   
1126       1.247  1885.0  473.6  130.4  39.98  1809.0  443.4  111.6  29.15   
1127       1.312  1882.0  473.6  130.5  39.69  1807.0  443.4  110.8  29.18   
1128       1.450  1884.0  474.2  131.0  40.12  1809.0  445.4  111.1  29.25   
1129       1.512  1887.0  479.1  131.0  39.96  1815.0  445.0  111.4  29.36   
1130       1.637  1886.0  480.2  131.4  40.24  1815.0  446.2  111.9  29.40   
1131       1.700  1888.0  477.4  131.0  40.15  1816.0  443.5  111.6  29.20   
1132       1.762  1890.0  472.6  130.3  39.70  1807.0  443.0  111.0  29.31   
1133       1.889  1891.0  474.5  129.7  39.64  1813.0  443.5  111.8  29.23   
1134       1.967  1875.0  476.0  129.6  39.51  1810.0  441.1  111.5  29.28   
1135       2.045  1876.0  475.5  129.9  39.54  1818.0  443.1  111.5  29.30   
1136       2.123  1872.0  475.5  130.1  39.93  1810.0  443.1  111.8  29.40   
1137       2.199  1877.0  473.7  129.3  39.71  1807.0  442.0  111.4  29.18   
1138       2.261  1874.0  472.4  129.4  39.60  1813.0  442.9  110.7  29.35   
1139       2.327  1887.0  471.8  129.8  39.69  1804.0  440.9  111.1  29.19   
1140       2.466  1887.0  476.9  129.4  39.75  1808.0  444.2  111.0  29.41   
...          ...     ...    ...    ...    ...     ...    ...    ...    ...   
1435      27.486  1828.0  464.8  128.0  39.09  1796.0  439.5  111.6  29.56   
1436      27.548  1831.0  461.2  128.3  39.29  1797.0  440.6  111.5  29.60   
1437      27.610  1837.0  463.8  128.6  39.39  1805.0  441.1  111.9  29.59   
1438      27.735  1837.0  464.3  128.8  39.40  1799.0  438.7  111.8  29.50   
1439      27.797  1847.0  463.4  128.4  39.24  1792.0  437.9  111.7  29.41   
1440      27.860  1834.0  462.7  127.9  38.92  1799.0  438.1  111.3  29.35   
1441      27.984  1821.0  460.9  127.8  38.79  1795.0  441.0  111.1  29.41   
1442      28.049  1825.0  462.2  127.8  39.02  1800.0  439.7  112.0  29.43   
1443      28.187  1829.0  462.2  128.2  39.12  1802.0  438.3  111.7  29.54   
1444      28.250  1838.0  465.7  128.1  39.18  1799.0  442.0  111.9  29.50   
1445      28.312  1835.0  462.3  128.4  39.20  1791.0  441.0  111.9  29.59   
1446      28.438  1834.0  464.7  128.4  39.42  1804.0  441.2  112.3  29.44   
1447      28.516  1836.0  464.7  128.6  39.56  1805.0  442.5  112.0  29.60   
1448      28.579  1854.0  466.5  129.8  39.61  1800.0  442.2  111.7  29.61   
1449      28.641  1834.0  463.3  128.2  39.28  1804.0  440.7  111.3  29.44   
1450      28.717  1829.0  460.0  128.8  39.17  1809.0  437.4  111.8  29.47   
1451      28.782  1833.0  462.8  128.2  39.14  1797.0  439.8  111.3  29.43   
1452      28.921  1829.0  463.0  127.8  39.19  1801.0  440.9  110.8  29.38   
1453      28.984  1820.0  461.7  128.0  39.36  1801.0  441.0  111.9  29.44   
1454      29.046  1835.0  46

In [14]:
"""Be able to merge a number of different datasets
    :param feature_dict_list: List of features to merge together
    
    :return merged dictionary
"""
def merge_features(feature_dict_list):
    main_dict = {}
    for feature_dict in feature_dict_list:
        for key in feature_dict.keys():
            if key in main_dict:
                main_dict[key] = main_dict[key] + feature_dict[key]
            else:
                main_dict[key] = feature_dict[key]
    return main_dict

In [15]:
features_902 = get_features_for_dataset("/Users/sjjin/workspace/hci_lab/data/S902/2015-02-26_11-24-48-120")
features_903 = get_features_for_dataset("/Users/sjjin/workspace/hci_lab/data/S903/2015-02-27_13-20-42-120")
features_904 = get_features_for_dataset("/Users/sjjin/workspace/hci_lab/data/S904/2015-02-27_15-30-27-120")
features_905 = get_features_for_dataset("/Users/sjjin/workspace/hci_lab/data/S905/2015-03-02_13-14-35-120")
features_906 = get_features_for_dataset("/Users/sjjin/workspace/hci_lab/data/S906/2015-03-05_11-17-38-120")

train_set = np.vstack([features_902, features_903, features_904, features_905])
test_set = features_906

In [16]:
train_set_x = train_set[:, :-1]
train_set_y = train_set[:, -1]
test_set_x = test_set[:, :-1]
test_set_y = test_set[:, -1]

In [28]:
pd = pd.

array([[-1.98423547e+00,  1.88085852e+03,  1.85117232e+03, ...,
        -1.55058519e-02,  1.25560231e+01,  1.23240395e+01],
       [-3.85560577e-01,  1.84479211e+03,  1.83903966e+03, ...,
        -1.38323870e-02,  1.26342789e+01,  1.24279037e+01],
       [-1.47441570e+00,  1.86788622e+03,  1.84582203e+03, ...,
        -1.90537288e-03,  1.23430331e+01,  1.23145198e+01],
       ...,
       [-2.39934402e+00,  1.14923396e+03,  1.11336158e+03, ...,
        -3.89149994e-02,  6.85373848e+00,  6.27192373e+00],
       [-3.33724264e+00,  1.11290992e+03,  1.06299718e+03, ...,
        -4.19361535e-02,  6.48779653e+00,  5.86058757e+00],
       [-5.67515709e-01,  1.08201662e+03,  1.07351412e+03, ...,
        -2.11510457e-02,  6.40478226e+00,  6.08789831e+00]])

In [17]:
len(train_set_y)

88

In [18]:
len(test_set_x)

21

In [19]:
clf = SVC(gamma='auto')
clf.fit(train_set_x, train_set_y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [20]:
test_set_x.shape

(21, 48)

In [21]:
result = clf.predict(test_set_x)
result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [22]:
accuracy_score(test_set_y, result)

0.5238095238095238

In [23]:
"""
"""
def plot_feature(table, feature_dict, column_name):
    x = table["Matlab_now"]
    y1 = table[column_name]
    feature = feature_dict[column_name]
    y2 = feature[0] * x + feature[1]

    plt.plot(x, y1)
    plt.plot(x, y2)
    plt.xlabel("time(s)")
    plt.ylabel("Light intensity")
    plt.title(column_name)
    plt.show()

In [24]:
"""
"""
def plot_feature(table, feature_dict, column_name):
    x = table["Matlab_now"]
    y1 = table[column_name]
    feature = feature_dict[column_name]
    y2 = feature[0] * x + feature[1]

    fig = plt.figure()
    ax = ax = fig.add_subplot(111)
    ax.plot(x, y1)
    ax.plot(x, y2)
    ax.set_xlabel("time(s)")
    ax.set_ylabel("Light intensity")
    ax.set_title(column_name)
    print(get_axis_limits(ax))
    #ax.annotate("text", get_axis_limits(ax))
    plt.show()

In [25]:
def get_axis_limits(ax, scale=0.9):
    return ax.get_xlim()[1]*scale, ax.get_ylim()[1]*scale

In [26]:
def plot_all_features(table, feature_dict):
    x = table["Matlab_now"]
    fig, ax = plt.subplots(nrows=4, ncols=4, figsize=(45, 45))

    count = 0
    for row in ax:
        for col in row:
            if (count == len(table.columns[1:].values)):
                break
            column_name = table.columns[1:].values[count]
    
            feature = feature_dict[column_name]
            
            y1 = table[column_name]
            y2 = feature[0] * x + feature[1]
            #y3 = [feature[2] for _ in range(len(y1))]
            

            col.plot(x, y1)
            col.plot(x, y2)
            col.set_xlabel("time(s)")
            col.set_ylabel("Light intensity")
            col.title.set_text(column_name)
            #my_text1 = "y = %f*x + %f" % (feature[0], feature[1])
            #my_text2 = "mean = %f" % (feature[2])
            my_text1 = "y = {:9.4f}*x + {:9.4f}".format(feature[0], feature[1])
            my_text2 = "mean = {:9.4f}".format(feature[2])
            col.text(0.3, 0.9, my_text1 , transform=col.transAxes, size=20, weight='bold')
            col.text(0.3, 0.8, my_text2 , transform=col.transAxes, size=20, weight='bold')

            count += 1
    #return ax.get_xlim()[1]*scale, ax.get_ylim()[1]*scale
    #ax1.annotate('A', xy=get_axis_limits(ax1))
    plt.savefig("fig1.png")
    plt.show()
